apiVersion: apps/v1
kind: Deployment
metadata:
  name: weave-gitops
  namespace: gitops
  labels:
    app: weave-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weave-gitops
  template:
    metadata:
      labels:
        app: weave-gitops
    spec:
      containers:
      - name: weave-gitops
        image: ghcr.io/weaveworks/wego-app
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"         # Maximum CPU usage (500 milliCPU = 0.5 vCPU)
            memory: "512Mi"     # Maximum memory usage (512 MiB)
          requests:
            cpu: "250m"         # Requested CPU (250 milliCPU = 0.25 vCPU)
            memory: "256Mi"     # Requested memory (256 MiB)
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
