apiVersion: v1
kind: Service
metadata:
  name: weave-gitops
  namespace: gitops
spec:
  selector:
    app: weave-gitops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
