apiVersion: apps/v1
kind: Deployment
metadata:
  name: capacitor
  namespace: capacitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capacitor
  template:
    metadata:
      labels:
        app: capacitor
    spec:
      containers:
        - name: capacitor
          image: ghcr.io/gimlet-io/capacitor:v0.4.3
          ports:
            - containerPort: 9000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
