apiVersion: v1
kind: Service
metadata:
  name: capacitor-service
  namespace: flux-system
spec:
  selector:
    app: capacitor
  ports:
    - port: 80  # This is the port exposed by the service
      targetPort: 8080  # This should match the containerPort in the Deployment
  type: ClusterIP  # Change to LoadBalancer if you need an external IP
