apiVersion: v1
kind: Service
metadata:
  name: capacitor-service
  namespace: flux-system
spec:
  selector:
    app.kubernetes.io/instance: capacitor
    app.kubernetes.io/name: capacitor
  ports:
    - port: 80  # This is the port exposed by the service
      targetPort: 9000  # This should match the containerPort in the Deployment
  type: ClusterIP  # Change to LoadBalancer if you need an external IP
