apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
resources:
  - helmrepository.yaml
  - helmrelease.yaml
  # - cluster-secret-store.yaml
  # - external-secret-test.yaml
