apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: prod-secret-store
  namespace: flux-system
resources:
  # - namespace.yaml
  - gitrepository.yaml
  - helmrelease.yaml
