# helm-repositories.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-repo
  namespace: flux-system
spec:
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loki-repo
  namespace: flux-system
spec:
  url: https://grafana.github.io/loki/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tempo-repo
  namespace: flux-system
spec:
  url: https://grafana.github.io/tempo/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-repo
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://grafana.github.io/helm-charts
