apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
  namespace: grafana
resources:
  - namespace.yaml 
  - helm-repositories.yaml
  - grafana-helmrelease.yaml
  # - loki-helmrelease.yaml
  # - prometheus-helmrelease.yaml
  # - tempo-helmrelease.yaml
