# tempo-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  releaseName: tempo
  chart:
    spec:
      chart: tempo
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: tempo-repo
        namespace: flux-system
  values:
    tempo:
      persistence:
        enabled: true
        size: 10Gi
