apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kp-stack
  namespace: kp-stack
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "68.4.4"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: kp-stack
  values:
    grafana:
      enabled: true
      additionalDataSources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.kp-stack.svc.cluster.local:3100
        - name: Tempo
          type: tempo
          access: proxy
          url: http://tempo.kp-stack.svc.cluster.local:3100
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
        additionalScrapeConfigs:
          - job_name: "loki"
            static_configs:
              - targets: ["loki.kp-stack.svc.cluster.local:3100"]
          - job_name: "tempo"
            static_configs:
              - targets: ["tempo.kp-stack.svc.cluster.local:3200"]
