apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: kp-stack
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - loki-helm-release.yaml
  - tempo-helm-release.yaml
 
