---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- infrastructure.yaml
- nodejs-hello-world.yaml
- capacitor-sync.yaml
- prod-secret-store.yaml
- ../../../kubernetes-dashboard/
# - ../../../production-fixfun/
# - kube-prometheus-stack.yaml
# - grafana.yaml
# - opentelemetry-collector.yaml
# - opentelemetry-demo.yaml
