apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
resources:
  - cert-manager.yaml
  - cluster-issuer.yaml
  - cronjon-freedomain-dns-update.yaml
  - flux-system-access-role.yaml
  - ./capacitor/namespace.yaml
  - capacitor-access-binding.yaml
  - ./capacitor/deployment.yaml
  - ./capacitor/service.yaml
  - ./capacitor/ingress.yaml
