apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
resources:
  - cert-manager.yaml
  - cluster-issuer.yaml
  - cronjon-cloudflare-dns-update.yaml
  # - ./capacitor/deployment.yaml
  # - ./capacitor/service.yaml
  # - ./capacitor/ingress.yaml
  # - namespace.yaml
  # - deployment.yaml
  # - ingress.yaml
