apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: my-opentelemetry-demo
  namespace: opentelemetry-demo
resources:
  - namespace.yaml
  - helmrelease.yaml
  - ingress.yaml
