apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: production-fixfun
  namespace: flux-system
resources:
  # - ghcr-secret.yaml
  - external-secret.yaml
  - gitrepository.yaml
  - helmrelease.yaml
