apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-helloworld
  namespace: nginx-helloworld
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - nginx-helloworld.goodhub.work.gd
      secretName: nginx-helloworld-tls-secret
  rules:
    - host: nginx-helloworld.goodhub.work.gd
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-helloworld
                port:
                  number: 80